### ISSUE TITLE
add dnsmasq+stubby menu option

### ISSUE THREAD

**Issue by aerth** [Nyr/wireguard-install#162]
awesome script. works especially great with dnsmasq+stubby on 10.7.0.1.

> 
> _[Stubby](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby) is an application that acts as a local DNS Privacy stub resolver (using DNS-over-TLS). Stubby encrypts DNS queries sent from a client machine (desktop or laptop) to a DNS Privacy resolver, increasing end user privacy._
> 
> _Stubby does not have a built-in DNS cache, therefore every single query is transmitted and resolved, which can slow down connections. Setting up a DNS cache requires installing and configuring a separate DNS cacher._

So, we can install stubby as secure resolver and dnsmasq to cache domains and serve to lo/wg0 clients.

Without menu support, need to modify each client.conf to use the wg server as resolver

eg: `DNS = 10.7.0.1`

for a menu option to install the dns packages and config files, could be a yesno or checkbox to add the already selected nameserver pair to stubby.yaml config

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 10.7.0.1:53             0.0.0.0:*               LISTEN      dnsmasq        
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      dnsmasq        
tcp        0      0 127.0.0.1:8053          0.0.0.0:*               LISTEN      stubby          
udp        0      0 127.0.0.1:8053          0.0.0.0:*                           stubby          
udp        0      0 127.0.0.1:53            0.0.0.0:*                           dnsmasq        
udp        0      0 10.7.0.1:53             0.0.0.0:*                           dnsmasq 
```

**Comment by aerth** [comment]
## test config
to test on a server, something like:

/etc/dnsmasq.d/wgdnsmasq.conf 
```ini
bogus-priv
domain-needed
no-resolv
log-queries
log-dhcp
no-hosts
interface=lo
listen-address=127.0.0.1,10.7.0.1
except-interface=lo
bind-interfaces
local=/home.arpa/
dnssec
proxy-dnssec
server=/bind/
server=/invalid/
server=/local/
server=/localhost/
server=/onion/
server=/test/
server=127.0.0.1#8053
cache-size=10000
```
/etc/stubby/stubby.yml
```yaml
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
  - GETDNS_TRANSPORT_TCP
  - GETDNS_TRANSPORT_UDP
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private : 1
round_robin_upstreams: 1
idle_timeout: 9000
listen_addresses:
  - 127.0.0.1:8053
dnssec: GETDNS_EXTENSION_TRUE
appdata_dir: "/run/stubby/"
trust_anchors_backoff_time: 2500
upstream_recursive_servers:
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 8.8.8.8
    tls_auth_name: "dns.google"
  - address_data: 8.8.4.4
    tls_auth_name: "dns.google"
```
